import Salade from "../../../../assets/salade.png";

export const fakeCategoriesMenu = [
    {
        id: 1,
        name : "Acompagnement",
        icon: "https://static.vecteezy.com/system/resources/previews/011/782/064/original/healthy-food-3d-render-icon-illustration-png.png",
    },
    {
        id: 2,
        name : "AfroBox",
        unity : "AfroBox",
        icon: "https://prettylittlepartyshop.co.uk/cdn/shop/products/kraft-burger-boxes-12-pack-cater-for-you-packaging-13993076850754.jpg?v=1658232948",
    },
    {
        id: 3,
        name : "Appéritifs",
        icon: "https://img.freepik.com/vecteurs-premium/aperitif-illustration-vectorielle-canape-3d-entree-collation-servie-assiette-maison-au-restaurant-style-dessin-anime-isole-fond-blanc-restaurant-menu-concept-alimentaire_778687-1197.jpg",
    },
    {
        id: 4,
        name : "Bières",
        icon: "https://cdn3d.iconscout.com/3d/premium/thumb/beer-mug-6220643-5102490.png?f=webp",
    },
    {
        id: 5,
        name : "Boisson maison",
        icon: "https://static.vecteezy.com/system/resources/previews/028/597/205/non_2x/drink-3d-rendering-icon-illustration-free-png.png",
    },
    {
        id: 6,
        name : "Boissons Chaudes",
        icon: "https://cdn.icon-icons.com/icons2/1447/PNG/512/32432hotbeverage_98916.png",
    },
    {
        id: 7,
        name : "Cocktails",
        icon: "https://cdn-icons-png.flaticon.com/512/6452/6452298.png",
    },
    {
        id: 8,
        name : "Desserts",
        icon: "https://i.pinimg.com/originals/9b/85/fb/9b85fba6644bef4a29da4d28168a49d7.jpg",
    },
    {
        id: 9,
        name : "Entrée",
        icon: "https://static.vecteezy.com/system/resources/previews/026/691/352/original/fried-egg-fast-food-meal-icon-isolated-3d-rendering-png.png",
    },
    {
        id: 10,
        name : "Formule",
        icon: "https://cdn3d.iconscout.com/3d/premium/thumb/food-menu-8666702-6909959.png",
    },
    {
        id: 11,
        name : "Grillades",
        icon: "https://cdn3d.iconscout.com/3d/premium/thumb/barbecue-6909266-5666854.png?f=webp",
    },
    {
        id: 12,
        name : "Plats",
        unity : "Plats",
        icon: "https://media.istockphoto.com/id/1190330112/photo/fried-pork-and-vegetables-on-white-background.jpg?s=612x612&w=0&k=20&c=TzvLLGGvPAmxhKJ6fz91UGek-zLNNCh4iq7MVWLnFwo=",
    },
    {
        id: 13,
        name : "Salades",
        icon: Salade,
    },
    {
        id: 14,
        name : "Sauce",
        icon: "https://media.istockphoto.com/id/1314356494/vector/realistic-detailed-3d-red-tomato-ketchup-bottle-and-basil-leaves-for-salad-vector.jpg?s=612x612&w=0&k=20&c=4m9L7DMh09ghsVU6DrU61W_I50-fe07YTgnIKrYsf1A=",
    },
    {
        id: 15,
        name : "Soft",
        icon: "https://img.freepik.com/premium-photo/mini-salted-pretzel-wood-plate-isolated-white-background-group-pretzel-mini-pretzel-snack_121658-1080.jpg",
    },
    {
        id: 16,
        name : "Vins",
        icon: "https://static.vecteezy.com/system/resources/previews/028/567/165/original/wine-glass-3d-rendering-icon-illustration-free-png.png",
    }
    
]
				
export const fakeProductsMenu = [
    {
        id: 1,
        name : "Allocos",
        unity : "La Portion",
        price: 3.50,
        iconProduct: "",
        description: "Banane plantain",
        creator_id: 1,
        tax: 10.000,
        cost: 0.70,
        category_id: 1
    },
    {
        id: 2,
        name : "Attieké",
        unity : "La Portion",
        price: 3.50,
        iconProduct: "",
        description: "Semoule de manioc",
        creator_id: 1,
        tax: 10.000,
        cost: 0.65,
        category_id: 1
    },
    {
        id: 3,
        name : "Chikwangue",
        unity : "La Pièce",
        price: 3.50,
        description: "Pâte de manioc",
        creator_id: 1,
        iconProduct: "",
        tax: 10.000,
        cost: 1.50,
        category_id: 1
    },
    {
        id: 4,
        name : "Frites de Patate douce",
        unity : "La Portion",
        price: 3.50,
        iconProduct: "",
        tax: 10.000,
        description: "Frites de patate douce",
        creator_id: 1,
        cost: 0.80,
        category_id: 1
    },
    {
        id: 5,
        name : "Grenailles de pomme de terre",
        unity : "La Portion",
        description: "Pomme de terre",
        creator_id: 1,
        price: 2.50,
        iconProduct: "",
        tax: 10.000,
        cost: 0.60,
        category_id: 1
    },
    {
        id: 6,
        name : "Riz Blanc",
        unity : "La Portion",
        description: "Riz",
        creator_id: 1,
        price: 2.50,
        iconProduct: "",
        tax: 10.000,
        cost: 0.50,
        category_id: 1
    },
    {
        id: 7,
        name : "Riz Djollof",
        unity : "La Portion",
        price: 3.50,
        description: "Riz",
        creator_id: 1,
        iconProduct: "",
        tax: 10.000,
        cost: 0.50,
        category_id: 1
    },
    {
        id: 8,
        name : "Abidjan Box",
        unity : "Par personne",
        description: "Dorade, Attieké, allocos",
        creator_id: 1,
        price: 13.90,
        iconProduct: "",
        tax: 0.000,
        cost: 10.00,
        category_id: 2
    },
    {
        id: 9,
        name : "Bamako Box",
        unity : "Par personne",
        description: "Mafé, poulet braisé, riz",
        creator_id: 1,
        price: 11.50,
        iconProduct: "",
        tax: 0.000,
        cost: 0.00,
        category_id: 2
    },
    {
        id: 10,
        name : "Elengi Brox",
        unity : "Par personne",
        description: "Nems, pastels, acras de morue",
        creator_id: 1,
        price: 11.50,
        iconProduct: "",
        tax: 0.000,
        cost: 0.00,
        category_id: 2
    },
    {
        id: 11,
        name : "La Sénégalaise Box",
        unity : "Par personne",
        description: "Yassa, poulet braisé, riz",
        creator_id: 1,
        price: 11.50,
        iconProduct: "",
        tax: 0.000,
        cost: 0.00,
        category_id: 2
    },
    {
        id: 12,
        name : "Mam's",
        unity : "Par personne",
        description: "Poulet braisé, patate",
        creator_id: 1,
        price: 11.50,
        iconProduct: "",
        tax: 0.000,
        cost: 0.00,
        category_id: 2
    },
    {
        id: 13,
        name : "Planteur Martiniquais",
        description: "Rhum, jus de fruits",
        creator_id: 1,
        unity : "Le Litre",
        price: 13.20,
        iconProduct: "",
        tax: 20.000,
        cost: 2.50,
        category_id: 3
    },
    {
        id: 14,
        name : "Bourbon Réunionaise 33cl",
        unity : "La Bouteille",
        description: "Bière",
        creator_id: 1,
        price: 5.00,
        iconProduct: "",
        tax: 20.000,
        cost: 1.47,
        category_id: 4
    },
    {
        id: 15,
        name : "Casablanca Marocaine 33cl",
        unity : "La Bouteille",
        description: "Bière",
        creator_id: 1,
        price: 5.00,
        iconProduct: "",
        tax: 20.000,
        cost: 1.45,
        category_id: 4
    },
    {
        id: 16,
        name : "Guiness Camérounaise 33cl",
        unity : "La Bouteille",
        price: 5.00,
        iconProduct: "",
        tax: 20.000,
        cost: 1.45,
        category_id: 4
    },
    {
        id: 17,
        name : "Phoenix Île maurice",
        unity : "La Bouteille",
        price: 5.00,
        iconProduct: "",
        tax: 20.000,
        cost: 1.45,
        category_id: 4
    },
    {
        id: 18,
        name : "Pression Blonde 25cl",
        unity : "Par verre",
        price: 3.50,
        iconProduct: "",
        tax: 20.000,
        cost: 0.75,
        category_id: 4
    },
    {
        id: 19,
        name : "Pression Desperados 25cl",
        unity : "Par verre",
        price: 4.00,
        iconProduct: "",
        tax: 20.000,
        cost: 1.00,
        category_id: 4
    },
    {
        id: 20,
        name : "THB Madagascar 33cl",
        unity : "La Bouteille",
        price: 5.00,
        iconProduct: "",
        tax: 20.000,
        cost: 1.40,
        category_id: 4
    },
    {
        id: 21,
        name : "THB Madagascar 33cl",
        unity : "La Bouteille",
        price: 5.00,
        iconProduct: "",
        tax: 20.000,
        cost: 1.40,
        category_id: 4
    },
    {
        id: 22,
        name : "Bissap",
        unity : "La Bouteille",
        description: "Jus maison à base d'hibiscus",
        creator_id: 1,
        price: 8.00,
        iconProduct: "",
        tax: 5.500,
        cost: 0.50,
        category_id: 5
    },
    {
        id: 23,
        name : "Gingembre",
        description: "Jus maison à base de gingembre",
        creator_id: 1,
        unity : "Par verre",
        price: 9.00,
        iconProduct: "",
        tax: 5.500,
        cost: 1.20,
        category_id: 5
    },
    {
        id: 24,
        name : "Café",
        unity : "Par verre",
        creator_id: 1,
        price: 2.00,
        iconProduct: "",
        tax: 5.500,
        cost: 0.25,
        category_id: 6
    },
    {
        id: 25,
        name : "Infusion Afrodetox avec alcool",
        unity : "Par verre",
        price: 7.00,
        creator_id: 1,
        iconProduct: "",
        tax: 20.000,
        cost: 1.80,
        category_id: 6
    },
    {
        id: 26,
        name : "Infusion Afrodetox sans alcool",
        unity : "Par verre",
        price: 5.00,
        creator_id: 1,
        iconProduct: "",
        tax: 5.500,
        cost: 1.00,
        category_id: 6
    },
    {
        id: 27,
        name : "Guavador avec alcool",
        unity : "Par verre",
        price: 8.50,
        iconProduct: "",
        creator_id: 1,
        tax: 20.000,
        cost: 2.00,
        category_id: 7
    },
    {
        id: 28,
        name : "Guavador Sans Alcool",
        unity : "Par verre",
        price: 6.50,
        iconProduct: "",
        creator_id: 1,
        tax: 5.500, 
        cost: 0.00,
        category_id: 7
    },
    {
        id: 29,
        name : "Karibu avec alcool",
        unity : "Par verre",
        price: 8.50,
        iconProduct: "",
        tax: 20.000,
        creator_id: 1,
        cost: 2.00,
        category_id: 7
    },
    {
        id: 30,
        name : "Karibu sans Alcool",
        creator_id: 1,
        unity : "Par verre",
        price: 6.50,
        iconProduct: "",
        tax: 5.500,
        cost: 1.50,
        category_id: 7
    },
    {
        id: 31,
        name : "Sap'rito avec alcool",
        unity : "Par verre",
        price: 8.50,
        iconProduct: "",
        tax: 20.000,
        creator_id: 1,
        cost: 2.00,
        category_id: 7
    },
    {
        id: 32,
        name : "Sap'rito sans alcool",
        unity : "Par verre",
        price: 6.50,
        creator_id: 1,
        iconProduct: "",
        tax: 5.500,
        cost: 1.50,
        category_id: 7
    },
    {
        id: 33,
        name : "Zanzibar avec Alcool",
        unity : "Par personne",
        price: 9.00,
        iconProduct: "",
        tax: 20.000,
        creator_id: 1,
        cost: 1.50,
        category_id: 7
    },
    {
        id: 34,
        name : "Zanzibar sans alcool",
        unity : "Par verre",
        creator_id: 1,
        price: 7.00,
        iconProduct: "",
        tax: 5.500,
        cost: 1.50,
        category_id: 7
    },
    {
        id: 35,
        name : "Entremets au coco",
        unity : "La Portion",
        price: 6.50,
        creator_id: 1,
        iconProduct: "",
        tax: 10.000,
        cost: 1.50,
        category_id: 8
    },
    {
        id: 36,
        name : "Gboflotos",
        unity : "La Portion",
        price: 6.00,
        creator_id: 1,
        iconProduct: "",
        tax: 10.000,
        cost: 1.00,
        category_id: 8
    },
    {
        id: 37,
        name : "Thiakry / Dèguè",
        unity : "La Portion",
        price: 6.00,
        creator_id: 1,
        iconProduct: "",
        tax: 10.000,
        cost: 1.00,
        category_id: 8
    },
    {
        id: 38,
        name : "Tiramisu Cacahuète",
        unity : "La Portion",
        price: 6.00,
        creator_id: 1,
        iconProduct: "",
        tax: 10.000,
        cost: 1.50,
        category_id: 8
    },
    {
        id: 39,
        name : "Tiramisu maison coco ananas",
        unity : "La Portion",
        price: 6.00,
        creator_id: 1,
        iconProduct: "",
        tax: 10.000,
        cost: 1.50,
        category_id: 8
    },
    {
        id: 40,
        name : "Accras de morue",
        unity : "La Pièce",
        price: 1.26,
        iconProduct: "",
        tax: 10.000,
        cost: 0.33,
        category_id: 9
    },
    {
        id: 41,
        name : "Achards de legumes aux Kosa-kosa",
        unity : "Par personne",
        price: 12.50,
        iconProduct: "",
        tax: 10.000,
        cost: 2.50,
        category_id: 9
    },
    {
        id: 42,
        name : "Assiette Exotique",
        unity : "Par personne",
        price: 12.80,
        iconProduct: "",
        tax: 10.000,
        cost: 2.50,
        category_id: 9
    },
    {
        id: 43,
        name : "Kosa-kosa",
        unity : "Par personne",
        price: 2.10,
        iconProduct: "",
        tax: 10.000,
        cost: 0.75,
        category_id: 9
    },
    {
        id: 44,
        name : "Les Yeux de Tountakhamon",
        unity : "La Pièce",
        price: 1.25,
        iconProduct: "",
        tax: 10.000,
        cost: 1.25,
        category_id: 9
    },
    {
        id: 45,
        name : "Nems Gasy",
        unity : "La Pièce",
        price: 1.95,
        iconProduct: "",
        tax: 10.000,
        cost: 0.75,
        category_id: 9
    },
    {
        id: 46,
        name : "Pastel Boeuf",
        unity : "La Pièce",
        price: 1.95,
        iconProduct: "",
        tax: 10.000,
        cost: 0.66,
        category_id: 9
    },
    {
        id: 47,
        name : "Pastel Thon",
        unity : "Par personne",
        price: 1.95,
        iconProduct: "",
        tax: 10.000,
        cost: 0.66,
        category_id: 9
    },
    {
        id: 48,
        name : "Pastel Vegan",
        unity : "La Pièce",
        price: 2.00,
        iconProduct: "",
        tax: 10.000,
        cost: 0.65,
        category_id: 9
    },
    {
        id: 49,
        name : "Samoussa",
        unity : "La Pièce",
        price: 2.00,
        iconProduct: "",
        tax: 10.000,
        cost: 0.35,
        category_id: 9
    },
    {
        id: 50,
        name : "Verrine Exotique",
        unity : "Par verre",
        price: 2.12,
        iconProduct: "",
        tax: 10.000,
        cost: 0.25,
        category_id: 9
    },
    {
        id: 51,
        name : "Verrine Exotique",
        unity : "Par verre",
        price: 2.12,
        iconProduct: "",
        tax: 10.000,
        cost: 0.25,
        category_id: 9
    },
    {
        id: 52,
        name : "Appéritif RN",
        unity : "Par personne",
        price: 6.00,
        iconProduct: "",
        tax: 10.000,
        cost: 2.00,
        category_id: 10
    },
    {
        id: 53,
        name : "Dessert",
        unity : "Par personne",
        price: 7.50,
        iconProduct: "",
        tax: 10.000,
        cost: 3.00,
        category_id: 10
    },
    {
        id: 54,
        name : "Enfant Diner",
        unity : "Par personne",
        price: 11.50,
        iconProduct: "",
        tax: 10.000,
        cost: 0.00,
        category_id: 10
    },
    {
        id: 55,
        name : "Entrée",
        unity : "Par personne",
        price: 9.50,
        iconProduct: "",
        tax: 10.000,
        cost: 2.50,
        category_id: 10
    },
    {
        id: 56,
        name : "Plat",
        unity : "Par personne",
        price: 18.00,
        iconProduct: "",
        tax: 10.000,
        cost: 4.00,
        category_id: 10
    },
    {
        id: 57,
        name : "1/2 Poulet Braisé",
        unity : "La Pièce",
        price: 9.90,
        iconProduct: "",
        tax: 10.000,
        cost: 2.20,
        category_id: 11
    },
    {
        id: 58,
        name : "Brochette de porc",
        unity : "La Pièce",
        price: 2.05,
        iconProduct: "",
        tax: 10.000,
        cost: 0.65,
        category_id: 11
    },
    {
        id: 59,
        name : "Brochettes de boeuf",
        unity : "La Pièce",
        price: 2.20,
        iconProduct: "",
        tax: 10.000,
        cost: 0.80,
        category_id: 11
    },
    {
        id: 60,
        name : "Cuisse de Poulet Braisé",
        unity : "La Pièce",
        price: 5.50,
        iconProduct: "",
        tax: 10.000,
        cost: 0.90,
        category_id: 11
    },
    {
        id: 61,
        name : "Cuisse de Poulet Braisée",
        unity : "La Pièce",
        price: 6.50,
        iconProduct: "",
        tax: 10.000,
        cost: 1.00,
        category_id: 11
    },
    {
        id: 62,
        name : "Dorade entière Braisée",
        unity : "La Pièce",
        price: 15.90,
        iconProduct: "",
        tax: 10.000,
        cost: 4.00,
        category_id: 11
    },
    {
        id: 63,
        name : "Aubergine à la morue",
        unity : "La Portion",
        price: 6.50,
        iconProduct: "",
        tax: 10.000,
        cost: 1.25,
        category_id: 12
    },
    {
        id: 64,
        name : "Dibi d'agneau à la sauce nubiènne",
        unity : "Par personne",
        price: 27.50,
        iconProduct: "",
        tax: 10.000,
        cost: 5.00,
        category_id: 12
    },
    {
        id: 65,
        name : "Liboké de Poisson",
        unity : "La Portion",
        price: 19.00,
        iconProduct: "",
        tax: 10.000,
        cost: 0.00,
        category_id: 12
    },
    {
        id: 66,
        name : "Mafé au boeuf",
        unity : "La Portion",
        price: 13.50,
        iconProduct: "",
        tax: 10.000,
        cost: 3.50,
        category_id: 12
    },
    {
        id: 67,
        name : "Mafé au poulet",
        unity : "La Portion",
        price: 15.00,
        iconProduct: "",
        tax: 10.000,
        cost: 3.50,
        category_id: 12
    },
    {
        id: 68,
        name : "Ndolé aux crevettes",
        unity : "La Portion",
        price: 8.20,
        iconProduct: "",
        tax: 10.000,
        cost: 4.20,
        category_id: 12
    },
    {
        id: 69,
        name : "Poêlé de Gombo aux Carottes",
        unity : "La Portion",
        price: 5.50,
        iconProduct: "",
        tax: 10.000,
        cost: 1.80,
        category_id: 12
    },
    {
        id: 70,
        name : "Pondu : Saka-Saka à la Sardine",
        unity : "La Portion",
        price: 6.20,
        iconProduct: "",
        tax: 10.000,
        cost: 2.00,
        category_id: 12
    },
    {
        id: 71,
        name : "Sauce Mafé",
        unity : "La Portion",
        price: 6.00,
        iconProduct: "",
        tax: 10.000,
        cost: 1.50,
        category_id: 12
    },
    {
        id: 72,
        name : "Sauce Yassa",
        unity : "La Portion",
        price: 6.50,
        iconProduct: "",
        tax: 10.000,
        cost: 1.50,
        category_id: 12
    },
    {
        id: 73,
        name : "Yassa au poulet",
        unity : "La Portion",
        price: 12.00,
        iconProduct: "",
        tax: 10.000,
        cost: 3.00,
        category_id: 12
    },
    {
        id: 74,
        name : "Achards de legumes",
        unity : "Par personne",
        price: 4.50,
        iconProduct: "",
        tax: 10.000,
        cost: 1.00,
        category_id: 13
    },
    {
        id: 75,
        name : "Salade Kachumbari",
        unity : "La Portion",
        price: 4.50,
        iconProduct: "",
        tax: 10.000,
        cost: 1.50,
        category_id: 13
    },
    {
        id: 76,
        name : "Salade Pharaon",
        unity : "La Portion",
        price: 15.00,
        iconProduct: "",
        tax: 10.000,
        cost: 2.50,
        category_id: 13
    },
    {
        id: 77,
        name : "Jawunta",
        unity : "La Portion",
        price: 0.60,
        iconProduct: "",
        tax: 10.000,
        cost: 0.12,
        category_id: 14
    },
    {
        id: 78,
        name : "Piment",
        unity : "La Portion",
        price: 0.60,
        iconProduct: "",
        tax: 10.000,
        cost: 0.10,
        category_id: 14
    },
    {
        id: 79,
        name : "Verte",
        unity : "La Portion",
        price: 0.60,
        iconProduct: "",
        tax: 10.000,
        cost: 0.10,
        category_id: 14
    },
    {
        id: 80,
        name : "Eau plate 1L",
        unity : "La Bouteille",
        price: 5.00,
        iconProduct: "",
        tax: 5.500,
        cost: 0.39,
        category_id: 15
    },
    {
        id: 81,
        name : "Eau plate 50cl",
        unity : "Par personne",
        price: 3.50,
        iconProduct: "",
        tax: 5.500,
        cost: 0.57,
        category_id: 15
    },
    {
        id: 82,
        name : "Champagne",
        unity : "La Bouteille",
        price: 32.40,
        iconProduct: "",
        tax: 20.000,
        cost: 4.50,
        category_id: 16
    }

]
